apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: monitoring-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "admin"
        admin-password: "{{ .password | toString }}"
  dataFrom:
    - extract:
        key: zvi/quizapp/key
      rewrite:
        - regexp:
            source: "grafana-pass"
            target: "password"
