apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: {{ .Values.app.namespaces }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1