apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://helm.elastic.co"
    chart: elasticsearch
    targetRevision: 7.17.3

    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1

        resources:
          requests:
            cpu: "100m"
            memory: "512M"
          limits:
            cpu: "1000m"
            memory: "1Gi"

        volumeClaimTemplate:
          storageClassName: standard
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true