apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: logging-secret
  namespace: logging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: logging-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: zvi/quizapp/key
        property: logging-user
    - secretKey: password
      remoteRef:
        key: zvi/quizapp/key
        property: logging-pass
