apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.45.0
    helm:
      values: |
        logLevel: info
        # luaScripts:
        #   setIndex.lua: |
        #     function set_index(tag, timestamp, record)
        #         index = "dakar-"
        #         if record["kubernetes"] ~= nil then
        #             if record["kubernetes"]["namespace_name"] ~= nil then
        #                 if record["kubernetes"]["container_name"] ~= nil then
        #                     record["es_index"] = index
        #                         .. record["kubernetes"]["namespace_name"]
        #                         .. "-"
        #                         .. record["kubernetes"]["container_name"]
        #                     return 1, timestamp, record
        #                 end
        #                 record["es_index"] = index
        #                     .. record["kubernetes"]["namespace_name"]
        #                 return 1, timestamp, record
        #             end
        #         end
        #         return 1, timestamp, record
        #     end
        ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush {{ .Values.flush }}
                Log_Level debug
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port {{ .Values.metricsPort }}
                Health_Check On
                Trace_Error On

          ## https://docs.fluentbit.io/manual/pipeline/inputs
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/rando*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 100MB
                Skip_Long_Lines On
            
            [INPUT]
                Name  tail
                Path  /var/log/containers/*nginx*.log
                multiline.parser docker, cri
                Parser nginx_ingress
                Tag    kube.nginx
                Mem_Buf_Limit 100MB
                Skip_Long_Lines On

            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter _SYSTEMD_UNIT=kubelet.service
                Read_From_Tail On

          ## https://docs.fluentbit.io/manual/pipeline/filters
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                Buffer_Size False
                K8S-Logging.Parser On
            
            [FILTER]
                Name kubernetes
                Match kube.nginx
                Merge_Log On
                Keep_Log Off
                Buffer_Size False
                K8S-Logging.Parser On
            
          ## https://docs.fluentbit.io/manual/pipeline/outputs
          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Index fluent-bit
                Type  _doc
                Host elasticsearch-master
                Port 9200
                HTTP_User elastic
                HTTP_Passwd 9fVpTSmmeC3IzEiE
                tls Off
                tls.verify Off
                Logstash_Format On
                Logstash_Prefix logstash
                Retry_Limit False
                Suppress_Type_Name On

            [OUTPUT]
                Name es
                Match kube.nginx
                Index fluent-bit
                Type  _doc
                Host elasticsearch-master
                Port 9200
                HTTP_User elastic
                HTTP_Passwd 9fVpTSmmeC3IzEiE
                tls Off
                tls.verify Off
                Logstash_Format On
                Logstash_Prefix logstash
                Retry_Limit False
                Suppress_Type_Name On

            [OUTPUT]
                Name es
                Match host.*
                Index fluent-bit
                Type  _doc
                Host elasticsearch-master
                Port 9200
                HTTP_User elastic
                HTTP_Passwd 9fVpTSmmeC3IzEiE
                tls Off
                tls.verify Off
                Logstash_Format On
                Logstash_Prefix node
                Retry_Limit False
                Suppress_Type_Name On

        customParsers: |
          [PARSER]
              Name   nginx_ingress
              Format regex
              Regex  ^(?<remote_addr>[^ ]+)\s+-\s+(?<remote_user>[^ ]*)\s+\[(?<time_local>[^\]]+)\]\s+"(?<method>\S+)\s+(?<uri>\S+)\s+(?<protocol>[^"]+)"\s+(?<status>\d{3})\s+(?<body_bytes_sent>\d+)\s+"(?<http_referer>[^"]*)"\s+"(?<http_user_agent>[^"]*)"\s+(?<request_length>\d+)\s+(?<request_time>[0-9.]+)\s+\[(?<upstream_name>[^\]]*)\]\s+\[(?<upstream_alt_name>[^\]]*)\]\s+(?<upstream_addr>[^\s]+)\s+(?<upstream_response_length>\d+)\s+(?<upstream_response_time>[0-9.]+)\s+(?<upstream_status>\d{3})\s+(?<request_id>[a-f0-9]+)
              Time_Key time_local
              Time_Format %d/%b/%Y:%H:%M:%S %z

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
